steps:
  # Cria um dataset no BigQuery usando o comando bq mk
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bq'
    args:
      - 'mk'
      - '--dataset'
      - '--location'
      - 'US'  # Substitua pela localização desejada
      - 'project-poc2025:dataset-cloudbuild'  # Substitua pelo ID do projeto e nome do dataset