steps:
  # Deploy Cloud Function
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'minha_funcao' # Nome da Cloud Function
      - '--runtime=python39' # Ou outra runtime de sua preferencia
      - '--trigger-http' # Tipo de gatilho
      - '--allow-unauthenticated' # Remova essa flag em produção, caso precise de autenticação.
      - '--region=us-central1' # Região de implantação
      - '--source=scripts/minha_funcao' # Caminho para o código da função