steps:
  # Cria um dataset no BigQuery
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'alpha'
      - 'bq'
      - 'datasets'
      - 'create'
      - 'project-poc2025:dataset-cloudbuild' # Substitua pelo ID do projeto e nome do dataset
      - 'US' # Substitua pela localização desejada