steps:
  # Cria o dataset no BigQuery (ignora erro se já existir)
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'bq mk --dataset --location US project-poc2025:datasetcloudbuild || echo "Dataset already exists"'

  # Cria uma tabela fictícia no BigQuery utilizando uma query SQL
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bq'
    args:
      - 'query'
      - '--nouse_legacy_sql'
      - >
        CREATE TABLE IF NOT EXISTS `project-poc2025.datasetcloudbuild.dummy_table` AS
        SELECT 1 AS id, "Alice" AS name, CURRENT_TIMESTAMP() AS created_at